# Generated by Django 5.0.6 on 2024-06-29 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_time', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarmHum', models.BooleanField()),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.nodes')),
            ],
        ),
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_air_quality', models.BooleanField()),
                ('air_quality_ppm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.nodes')),
            ],
        ),
        migrations.CreateModel(
            name='temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarmTemp', models.BooleanField()),
                ('temp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.nodes')),
            ],
        ),
    ]
